# -*- coding: utf-8 -*-
"""q1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10e_NvY6vTdzDzeSuSlGKvjRDPpYAkEh_
"""

lista=[1,2,3,2,4,2]
print(lista.count(2))