# -*- coding: utf-8 -*-
"""q2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10e_NvY6vTdzDzeSuSlGKvjRDPpYAkEh_
"""

lista=[10,20,10]
soma=0
for i in range(len(lista)):
  soma=lista[i]+soma
print(soma/len(lista))