# -*- coding: utf-8 -*-
"""q3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10e_NvY6vTdzDzeSuSlGKvjRDPpYAkEh_
"""

lista=[1,2,3,4,5]
print(f"maior:{max(lista)} e menor:{min(lista)}")