# -*- coding: utf-8 -*-
"""q4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10e_NvY6vTdzDzeSuSlGKvjRDPpYAkEh_
"""

lista=[1,2,3,4]
lista2=[]
for i in range(len(lista)):
  if lista[i]%2==0:
    lista2.append(lista[i])
print(lista2)