# -*- coding: utf-8 -*-
"""q5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10e_NvY6vTdzDzeSuSlGKvjRDPpYAkEh_
"""

lista3=[]
lista1=input().split()
lista2=input().split()
for i in range(len(lista1)):
  lista3.append(int(lista1[i]))
for i in range(len(lista2)):
  lista3.append(int(lista2[i]))
lista3.sort()
print(lista3)